### ISSUE TITLE
Possible EventEmitter Memory leak

### ISSUE THREAD

**Issue by robblovell** [noodlefrenzy/node-amqp10#161]
The following code results in an error from node.  Note that the event hub has 32 partitions.
```coffeescript
require('events').EventEmitter.prototype._maxListeners = 100 # without this, receiver gives an error right away at 11 listeners.
AMQPClient = require('amqp10')
client = new AMQPClient(AMQPClient.policies.EventHubPolicy)
process = (ix, addr) ->
    client.receive(addr, undefined, (err, payload, annotations) ->
        if (err)
            console.log('ERROR: ')
            console.log(err)
        else
            console.log('Recv(' + ix + ', '+ addr + '): ')
            console.log(payload.MessageId)
            console.log(payload.Revision)
            if (annotations)
                console.log('Annotations:');
                console.log(annotations);
    )
client.connect(config.uri, () ->
    curRcvAddr = []
    for idx in [0...config.numPartitions]
        process(idx,config.recvAddr + idx )
)
```
Here's the error:
```javascript
(node) warning: possible EventEmitter memory leak detected. 101 Link.Attached listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at AMQPClient.addListener (events.js:179:15)
    at AMQPClient.receive.attach (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:497:10)
    at AMQPClient.receive (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:544:7)
    at process (/Users/robblovell/Code/Platform-Test-Harness/app.js:41:19)
    at /Users/robblovell/Code/Platform-Test-Harness/app.js:62:20
    at Connection.<anonymous> (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:218:5)
    at Connection.emit (events.js:107:17)
    at Connection._processError (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/connection.js:355:8)
    at Object.errorHandler (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/connection.js:290:43)
    at Object.event (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/node_modules/stately.js/Stately.js:206:67)

/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/session.js:273
  throw new exceptions.OverCapacityError('Out of available handles (Max = ' + 
        ^
Error: Out of available handles (Max = 255)
    at new OverCapacityError (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/exceptions.js:83:9)
    at Session._nextHandle (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/session.js:273:9)
    at Session.attachLink (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/session.js:200:32)
    at AMQPClient.receive.attach (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:506:21)
    at AMQPClient.receive (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:544:7)
    at process (/Users/robblovell/Code/Platform-Test-Harness/app.js:41:19)
    at /Users/robblovell/Code/Platform-Test-Harness/app.js:62:20
    at Connection.<anonymous> (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:218:5)
    at Connection.emit (events.js:107:17)
    at Connection._processError (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/connection.js:355:8)

Process finished with exit code 1
```

Without the modification of _MaxListners, the code gives this error right at startup but continues on:
```javascript
(node) warning: possible EventEmitter memory leak detected. 11 Link.Attached listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at AMQPClient.addListener (events.js:179:15)
    at AMQPClient.receive.attach (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:497:10)
    at AMQPClient.receive (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:544:7)
    at process (/Users/robblovell/Code/Platform-Test-Harness/app.js:39:19)
    at /Users/robblovell/Code/Platform-Test-Harness/app.js:60:20
    at Session.<anonymous> (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/amqp_client.js:165:7)
    at Session.emit (events.js:107:17)
    at Session._beginReceived (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/session.js:379:8)
    at Session._processFrame (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/session.js:281:12)
    at Connection.Session.begin._processFrameEH (/Users/robblovell/Code/Platform-Test-Harness/node_modules/amqp10/lib/session.js:190:49)
```

**Comment by mbroadst** [comment]
@robblovell I wonder if you might be interested in trying out v2.0.0 of the module? You can update to that using a commit-ish entry (vs number) in your package.json dependencies:
```
"dependencies": {
   "amqp10": "noodlefrenzy/node-amqp10#master"
}
```

The API has slightly changed (mostly due to promisifying all the things), but there have been a number of critical improvements to the codebase. While the documentation is still out of date, all of the examples in master have been updated and the integration tests should also be useful.

**Comment by robblovell** [comment]
@mbroadst  Brilliant. 

I tried it out and the "EventEmitter memory leak detected." is no longer happening. 

Running it for 30 minutes and the "Out of available handles" hasn't occurred. 

I am losing this, but will continue to run my test over the next few hours. If the error shows up after a long period, I will reopen.
