### ISSUE TITLE
can't set property absoluteExpiryTime on AMQP message

### ISSUE THREAD

**Issue by damonbarry** [noodlefrenzy/node-amqp10#177]
When I pass the following object to the `SenderLink.send` method:
```javascript
AmqpMessage {
  properties: {
    absoluteExpiryTime: 1445475982850,
    to: '/devices/dlbtest01/messages/devicebound'
  },
  body: '\'hello\''
}
```
...in the resulting message sent over AMQP the absoluteExpiryTime is `undefined`:
```javascript
Message {
  properties: Properties {
    descriptor: [Int64 value:115 octets:00 00 00 00 00 00 00 73],
    value: undefined,
    to: '/devices/dlbtest01/messages/devicebound',
    absoluteExpiryTime: undefined
  },
  body: <Buffer 27 68 65 6c 6c 6f 27>
}
```
This is because the Properties constructor in /lib/types/message.js maps `absoluteExpiryTime` to `absoluteExpiryT`:
```javascript
    absoluteExpiryTime: options.absoluteExpiryT,
```
If I fix that by adding `ime` to the end, then I get the following exception:
```
f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\types.js:601
                throw new errors.NotImplementedError('buffer-builder does not support 64-bit int appending');
                ^
AmqpNotImplementedError: buffer-builder does not support 64-bit int appending not yet implemented
    at Object.typesArray.encodings.builder (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\types.js:601:23)
    at self.builders.(anonymous function) (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\types.js:814:38)
    at Codec.encode (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\codec.js:192:12)
    at Codec.encode (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\codec.js:237:21)
    at f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\types.js:90:11
    at Array.forEach (native)
    at Types._listBuilder (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\types.js:89:8)
    at Codec.encode (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\codec.js:233:16)
    at Codec.encode (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\codec.js:261:21)
    at Codec.encode (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\codec.js:241:14)
    at Message.encode (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\types\message.js:364:30)
    at Codec.encode (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\codec.js:263:13)
    at TransferFrame.AMQPFrame._writePayload (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\frames\frame.js:183:11)
    at TransferFrame.Frame.write (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\frames\frame.js:74:8)
    at Connection.sendFrame (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\connection.js:336:9)
    at SenderLink._sendMessage (f:\azure-iot-sdks\node\service\node_modules\amqp10\lib\sender_link.js:164:27)
```
I'd like to be able to set absoluteExpiryTime on AMQP messages.  Is it a simple thing to "support 64-bit int appending", or not so much?

**Comment by mbroadst** [comment]
@damonbarry this is an easy fix, but I need until tomorrow morning to get the full fix in with tests. The short answer to your problem is: yes you need to fix that typo (whoops!), and secondly you are passing a number with too fine precision into that property so our codec is picking it up as an attempted 64bit (or rather as close as javascript can come to expressing such numbers). If you can't wait for my fix tomorrow, then a quick solution would be to chop some precision off the number. For example, you might instead use:

```
sender.send("hello", {
  properties: {
    absoluteExpiryTime: Math.floor( Date.now() / 1000 ),
    to: '/devices/dlbtest01/messages/devicebound'
});
```

**Comment by damonbarry** [comment]
I can wait, no worries!

**Comment by mbroadst** [comment]
@damonbarry hey, just committed a fix. We used to drop support for any numbers whose absolute value was greater than `2^32 - 1`, just so we could absolutely ensure support. I've broken the shackles, and now we just try to support as much precision as possible (with a potential for silently dropped precision atm, unfortunately). Hope this helps!

**Comment by damonbarry** [comment]
Confirmed it's working as expected now, thanks!

**Comment by mbroadst** [comment]
@damonbarry great news :+1:

I'm waiting on a review from @noodlefrenzy before publishing the point release, shouldn't be too much time.
