### ISSUE TITLE
Bugs surfacing when running EventHub/ServiceBus integration tests without environment variables.

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/node-amqp10#197]
```
  3) ServiceBus EventHubs should send to a specific partition:
     Uncaught TypeError: Cannot call method 'destroy' of null
      at Connection._terminate (lib/connection.js:9:24820)
  4) ServiceBus EventHubs "after each" hook:
     Uncaught TypeError: Property '_reconnect' of object #<AMQPClient> is not a function
      at AMQPClient._attemptReconnection (lib/amqp_client.js:9:15004)
      at null._onTimeout (lib/amqp_client.js:9:5088)
```

These look bad, fix them.

**Comment by mbroadst** [comment]
@noodlefrenzy I think this is probably fixed by https://github.com/noodlefrenzy/node-amqp10/commit/8eeeb5bfecc9f5fddbf16fea22d0f97eb1533dca ?

**Comment by noodlefrenzy** [comment]
Yes it is, good catch.
