### ISSUE TITLE
Issue with Azure Iot Hub Code 

### ISSUE THREAD

**Issue by dmoreland** [noodlefrenzy/node-amqp10#212]
```
TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\frames.js:41:9)
    at Connection.sendFrame (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\connection.js:336:10)
    at ReceiverLink.Link.attach (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:102:27)
    at ReceiverLink.Link._attemptReattach (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:205:8)
    at null._onTimeout (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:193:10)
    at Timer.listOnTimeout (timers.js:92:15)
```
After leaving my code sending messages to Azure after about an hour i get this,

**Comment by noodlefrenzy** [comment]
I _think_ this is due to SAS Token expiry and the fact that IoT Hub doesn't auto-renew (yet). Looping in @pierreca to weigh in.

However, I agree that this method of erroring out sucks. Which is why I opened this https://github.com/noodlefrenzy/node-amqp10/issues/201 against us.

**Comment by mbroadst** [comment]
This is definitely an issue with our code, but I'm unsure as to whether its correctly identified as a bug in the reconnect logic (if that is enabled) or rather that we are simply not throwing an error where we should be. I've seen this a number of times in my own code that is just connected to qpidd, it seems that the underlaying connection for the link has died somehow (I suspect something that calls `AMQPClient. _clearConnectionState`), and its still trying to use that

**Comment by pierreca** [comment]
yes, this happening after 1 hour strongly suggest something is wrong with our SAS token renewal logic. looking into it from https://github.com/Azure/azure-iot-sdks/issues/320 as well.

**Comment by mbroadst** [comment]
@dmoreland @pierreca this should be "handled" by https://github.com/noodlefrenzy/node-amqp10/commit/8eeeb5bfecc9f5fddbf16fea22d0f97eb1533dca, however it remains to be seen whether renewal of the token properly takes place now that the code isn't bombing out on an unhandled exception.

**Comment by mbroadst** [comment]
@dmoreland @pierreca ping. are you still experiencing this issue after having updated node-amqp10?

**Comment by pierreca** [comment]
@mbroadst I think we're all good from your perspective. I'm now using the correct policies to not reattach and the commit you referenced fixes the problem on your side. 
Also FYI, since v 1.0.0 we do renew the SAS token automatically :) not in the most elegant fashion but we do :)

**Comment by mbroadst** [comment]
@pierreca cool, good to know :smile:
