### ISSUE TITLE
`make coverage` failing on master

### ISSUE THREAD

**Issue by dnwe** [noodlefrenzy/node-amqp10#253]
This appears to be failing both on Travis and on local `make coverage` runs.

```
$ make coverage
./node_modules/.bin/jshint lib test tools examples
./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- --recursive -t 30000 --ui tdd ./test/unit ./test/integration/qpid ./test/integration/servicebus
=============================================================================
Writing coverage object [/home/travis/build/noodlefrenzy/node-amqp10/coverage/coverage.json]
Writing coverage reports at [/home/travis/build/noodlefrenzy/node-amqp10/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 24.99% ( 597/2389 )
Branches     : 3.19% ( 36/1128 )
Functions    : 8.73% ( 37/424 )
Lines        : 26.15% ( 591/2260 )
================================================================================

/home/travis/build/noodlefrenzy/node-amqp10/node_modules/chai/lib/chai/assertion.js:107
      throw new AssertionError(msg, {
      ^
AssertionError: Missing env serviceBusHost: expected undefined to exist
    at Assertion.<anonymous> (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/chai/lib/chai/core/assertions.js:389:10)
    at Assertion.addProperty (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/chai/lib/chai/utils/addProperty.js:43:29)
    at /home/travis/build/noodlefrenzy/node-amqp10/test/testing_utils.js:13:64
    at Array.forEach (native)
    at Object.populateConfig (/home/travis/build/noodlefrenzy/node-amqp10/test/testing_utils.js:12:29)
    at Object.<anonymous> (/home/travis/build/noodlefrenzy/node-amqp10/test/integration/servicebus/queues/config.js:4:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/noodlefrenzy/node-amqp10/test/integration/servicebus/queues/client.test.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/travis/build/noodlefrenzy/node-amqp10/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/mocha/bin/_mocha:457:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at runFn (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/node_modules/async/lib/async.js:361:13
    at /home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
    at /home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /home/travis/build/noodlefrenzy/node-amqp10/node_modules/istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1530:14)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
make: *** [coverage] Error 1


The command "make coverage" exited with 2.
```

**Comment by dnwe** [comment]
(actually the local ones I'm guessing its just because I haven't set serviceBusHost env, but I assume Travis is meant to be able to run these?)

**Comment by dnwe** [comment]
Ah yes, I see from the main master travis build log:
```
Setting environment variables from repository settings:
$ export ServiceBusNamespace=[secure]
$ export EventHubName=[secure]
$ export EventHubPartitionCount=[secure]
$ export EventHubKeyName=[secure]
$ export EventHubKey=[secure]
$ export ServiceBusQueueKeyName=[secure]
$ export ServiceBusQueueName=[secure]
$ export ServiceBusQueueKey=[secure]
$ export CODECLIMATE_REPO_TOKEN=[secure]
$ export ServiceBusQueueKeys=[secure]
$ export ServiceBusQueueNames=[secure]
$ export ServiceBusQueueKeyNames=[secure]
$ export ValidProcessVersions="v0.1.?0*|v0.1.?2*|v4*|v5*|v6*"
```

However, this does mean that the status checks on pull requests will always fail?

**Comment by mbroadst** [comment]
@dnwe yes, to conserve resource usage on the ServiceBus/EventHub servers that @noodlefrenzy set up, these values are only injected on the main repo. As a consequence, PRs that aren't from us will fail, which generally wasn't a problem since we were the only ones committing to the repo.

If you don't mind, a very simply solution could be implemented to simply `skip` those tests instead of throwing an error. In cases like these: https://github.com/noodlefrenzy/node-amqp10/blob/master/test/integration/servicebus/eventhubs/client.test.js#L31, there is an expectation set for the required variables, which could be replaced with a call to `this.skip()` (I believe), or an approach I've taken previously has been to set up an alias for `it` at the top of the script similar to: `let maybeTest = (!!process.env.VARIABLE) ? it : it.skip;  maybeTest('some suite', () => {});`

**Comment by dnwe** [comment]
@mbroadst out of interest is there any automation for standing up the resources in azure needed to run the suite, or is it just default config?

**Comment by mbroadst** [comment]
You'd have to speak to @noodlefrenzy about that, but I believe it can be set up somewhat easily with the basic credits provided with a developer account. I'll let him chime in, but he might be out of town for a bit here.

**Comment by dnwe** [comment]
Happy to close this one off now that the servicebus tests are just being skipped if the env vars aren't available. Thanks @mbroadst
