### ISSUE TITLE
No callback triggered on ECONNREFUSED

### ISSUE THREAD

**Issue by tirithen** [noodlefrenzy/node-amqp10#258]
Hi, I'm having troubles that the promise rejection callback is not executed when the connection fails, if I run with DEBUG=amqp* I get these repeated logs:

```
  amqp10:client connecting to: amqp://localhost +0ms
  amqp10:transport:net Connecting to localhost:5672 via straight-up sockets +5ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +3ms
  amqp10:connection Error from socket: Error: connect ECONNREFUSED 127.0.0.1:5672 +2ms
  amqp10:client connection error:  +1ms { Error: connect ECONNREFUSED 127.0.0.1:5672
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672 }
  amqp10:client disconnected +9ms
  amqp10:connection Transitioning from START to DISCONNECTED due to error +1ms

```

I need to have a working error callback somewhere but it never seem to trigger. In desperation I added client.on('error', () => {}) without knowing if that even exists.

The code that I use are:

```
const AMQP = require('amqp10');

const AMQP_HOST = process.env.AMQP_HOST || 'localhost';

this.client = new AMQP.Client(AMQP.ActiveMQ);
this.client.connect(`amqp://${AMQP_HOST}`).then(() => {
  console.log('connected', `amqp://${AMQP_HOST}`);
  this.client.createReciever('log').then((reciever) => {
    console.log('reciever created');
    reciever.on('message', (message) => {
      const level = message.level === 'warning' ? 'warn' : message.level;

      if (console[level] instanceof Function) {
        if (message.package) {
          console[level](
            (new Date(message.date).toISOString()),
            message.package.name,
            message.package.version,
            message.level,
            message.data
          );
        } else {
          console[level](
            (new Date(message.date).toISOString()),
            message.level,
            message.data
          );
        }
      }
    });
  }, (error) => {
    console.error(error);
    throw new Error('Unable to create a reciever for the amqp service, exiting');
  });
}, (error) => {
  console.error(error);
  throw new Error('Unable to connect to amqp service, exiting');
});

this.client.on('error', () => {
  console.error(error);
  throw new Error('Connection to amqp service whent down, exiting');  
});

console.log('Test that we get here', `amqp://${AMQP_HOST}`);

```

**Comment by tirithen** [comment]
I found something that might be the answer, if I set the event listener to

this.client.on(AMQP.Client.ErrorReceived, error => console.error(error));

**Comment by mbroadst** [comment]
@tirithen this is most likely because you have reconnect set to retry forever (the default). You could for instance try: `this.client = new AMQP.Client({ reconnect: { retries: 1, forever: false } });`

**Comment by tirithen** [comment]
Also thanks for fast response :)
