### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'write' of null

### ISSUE THREAD

**Issue by Finkes** [noodlefrenzy/node-amqp10#307]
Hi I use this library to connect to Microsoft Azure Service Bus. Sometimes my connection crashes and then I try to call disconnect before reconnecting again. Then I receive following error: 

 ```
Unhandled rejection TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (/path/to/project/node_modules/amqp10/lib/frames.js:56:9)
    at Connection.sendFrame (/path/to/project/node_modules/amqp10/lib/connection.js:328:10)
    at Connection._sendCloseFrame (/path/to/project/node_modules/amqp10/lib/connection.js:490:8)
    at Object.Connection.stateMachine.CLOSE_RCVD.sendClose (/path/to/project/node_modules/amqp10/lib/connection.js:263:14)
    at Object.event [as sendClose] (/path/to/project/node_modules/stately.js/Stately.js:203:67)
    at Connection.close (/path/to/project/node_modules/amqp10/lib/connection.js:323:15)
    at /path/to/project/node_modules/amqp10/lib/amqp_client.js:364:18
    at Promise._execute (/path/to/project/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/path/to/project/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/path/to/project/node_modules/bluebird/js/release/promise.js:77:14)
    at AMQPClient.disconnect (/path/to/project/node_modules/amqp10/lib/amqp_client.js:352:10)
```

**Comment by wingedfox** [comment]
Here's how to reproduce the error

- run webcenter/activemq container (as of today)
- start app and request amqp connection

this will end up with the following
```
2017-03-17T11:14:47.098Z - info: [log] [amqpConnection] Create new connection for "amqp://admin:****@172.17.0.2:61616"
  amqp10:client connecting to: amqp://admin:admin@172.17.0.2:61616 +0ms
  amqp10:transport:net Connecting to 172.17.0.2:61616 via straight-up sockets +6ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +1ms
  amqp10:connection Sending Header 414d515003010000 +10ms
  amqp10:connection Transitioning from START to IN_SASL due to connected +0ms
  amqp10:connection Rx: 00000183014163746976654d510000000c01000001710000000c00115463704e6f44656c6179456e61626c65640101001253697a6550726566697844697361626c656401000009436163686553697a650500000400000c50726f76696465724e616d650900084163746976654d510011537461636b5472616365456e61626c65640101000f506c6174666f726d44657461696c7309004c4a564d3a20312e382e305f39312c2032352e39312d6231342c204f7261636c6520436f72706f726174696f6e2c204f533a204c696e75782c20342e342e362d67656e746f6f2c20616d643634000c4361636865456e61626c6564010100145469676874456e636f64696e67456e61626c65640101000c4d61784672616d6553697a6506000000000640000000154d6178496e61637469766974794475726174696f6e06000000000000753000204d6178496e61637469766974794475726174696f6e496e6974616c44656c6179060000000000002710000f50726f766964657256657273696f6e090006352e31342e33 +31ms
  amqp10:sasl Server SASL Version: 0000018301416374 vs 414d515003010000 +1ms
  amqp10:connection Error from socket: AmqpMalformedHeaderError: malformed header: Invalid SASL Header 0000018301416374 +2ms
  amqp10:client connection error:  { AmqpError: malformed header: Invalid SASL Header 0000018301416374
    at Sasl.headerReceived (/node_modules/amqp10/lib/sasl.js:58:19)
    at Connection._tryReceiveHeader (/node_modules/amqp10/lib/connection.js:373:17)
    at Connection._receiveAny (/node_modules/amqp10/lib/connection.js:403:17)
    at Connection._receiveData (/node_modules/amqp10/lib/connection.js:357:8)
    at NetTransport.<anonymous> (/node_modules/amqp10/lib/connection.js:515:38)
    at emitOne (events.js:96:13)
    at NetTransport.emit (events.js:189:7)
    at Socket.<anonymous> (/node_modules/amqp10/lib/transport/net_transport.js:26:49)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'AmqpMalformedHeaderError',
  message: 'malformed header: Invalid SASL Header 0000018301416374' } +0ms
2017-03-17T11:14:47.153Z - warn: [log] [amqpConnection] AMQP connection:errorReceived AmqpError: malformed header: Invalid SASL Header 0000018301416374
    at Sasl.headerReceived (/node_modules/amqp10/lib/sasl.js:58:19)
    at Connection._tryReceiveHeader (/node_modules/amqp10/lib/connection.js:373:17)
    at Connection._receiveAny (/node_modules/amqp10/lib/connection.js:403:17)
    at Connection._receiveData (/node_modules/amqp10/lib/connection.js:357:8)
    at NetTransport.<anonymous> (/node_modules/amqp10/lib/connection.js:515:38)
    at emitOne (events.js:96:13)
    at NetTransport.emit (events.js:189:7)
    at Socket.<anonymous> (/node_modules/amqp10/lib/transport/net_transport.js:26:49)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  amqp10:client disconnected +2ms
2017-03-17T11:14:47.154Z - warn: [log] [amqpConnection] AMQP connection:closed
  amqp10:connection Transitioning from IN_SASL to DISCONNECTED due to error +1ms
  amqp10:framing sending frame:  @close(24) [error={ condition: 'connection:framing-error',
  description: 'malformed header: Invalid DOFF' }] +2ms
  amqp10:trace raw: [0000005602000000005318c0490100531dc04303a31d616d71703a636f6e6e656374696f6e3a6672616d696e672d6572726f72a11e6d616c666f726d6564206865616465723a20496e76616c696420444f4646c10100] +0ms
/node_modules/amqp10/lib/frames.js:56
  stream.write(buffer, callback);
        ^

TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (/node_modules/amqp10/lib/frames.js:56:9)
    at Connection.sendFrame (/node_modules/amqp10/lib/connection.js:328:10)
    at Connection._sendCloseFrame (/node_modules/amqp10/lib/connection.js:490:8)
    at Connection._receiveAny (/node_modules/amqp10/lib/connection.js:412:12)
    at Connection._receiveData (/node_modules/amqp10/lib/connection.js:357:8)
    at NetTransport.<anonymous> (/node_modules/amqp10/lib/connection.js:515:38)
    at emitOne (events.js:96:13)
    at NetTransport.emit (events.js:189:7)
    at Socket.<anonymous> (/node_modules/amqp10/lib/transport/net_transport.js:26:49)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by wingedfox** [comment]
It's even easier to reproduce. This happens when connecting to any service which talks anything, but Amqp 1.0.
With the contained mentioned above it was a long container start.

**Comment by mbroadst** [comment]
@wingedfox I think you're running into an unrelated case where the underlaying connection is attempted to be reused before a reconnect completes (in your case because sasl auth has failed). Unfortunately, the failure point is the same for so many of these cases so they all look like the same problem - however they have different root causes.  I'm trying to do some rewrites of our internal state machines in order to better handle reconnection/reattachment which should alleviate some (if not all) of these issues (#303, #295, #291, etc), like  but am limited by time availability.

**Comment by wingedfox** [comment]
@mbroadst, if you can describe target solution I can try to help with the implementation.

**Comment by BretStateham** [comment]
I am running into this issue as well intermittently using the Azure IoT Hubs.  

The script I'm using is here: https://github.com/Mission-Mars-Fourth-Horizon-Org/CoffeePotDevice/blob/master/CoffeeClient/node/readdevicetocloudmessages/ReadDeviceToCloudMessages.js  .  The code is basically just the code created during the [Connect your simulated device to your IoT hub using Node](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted) walkthrough in the Azure Docs.

Here's a .zip with my actual code:
[ReadDeviceToCloudMessages.zip](https://github.com/noodlefrenzy/node-amqp10/files/1122676/ReadDeviceToCloudMessages.zip)

The current version of the libraries used by the app are:

```bash
readdevicetocloudmessages
└─┬ azure-event-hubs@0.0.7
  ├─┬ amqp10@3.5.0
  │ ├─┬ bl@1.2.1
  │ │ └─┬ readable-stream@2.3.3
  │ │   ├── core-util-is@1.0.2
  │ │   ├── inherits@2.0.3
  │ │   ├── isarray@1.0.0
  │ │   ├── process-nextick-args@1.0.7
  │ │   ├── safe-buffer@5.1.1
  │ │   ├── string_decoder@1.0.3
  │ │   └── util-deprecate@1.0.2
  │ ├── buffer-builder@0.2.0
  │ ├─┬ debug@2.6.8
  │ │ └── ms@2.0.0
  │ ├── lodash@4.17.4
  │ ├── node-int64@0.4.0
  │ └── stately.js@1.3.0
  ├─┬ azure-iot-common@1.1.3
  │ └── crypto@0.0.3
  ├── bluebird@3.5.0
  └── uuid@3.1.0
```
The problem happens intermittently.  The program will crash immediately after initializing the consumer on each partition.  I can try it a few times by ctrl-c 'ing out and re-running and finally it will work usually after 2-4 attempts.
