### ISSUE TITLE
TypeError: Cannot read property 'write' of null

### ISSUE THREAD

**Issue by jtjk** [noodlefrenzy/node-amqp10#322]
Wed May 17 2017 19:19:23 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (D:\home\site\wwwroot\node_modules\amqp10\lib\frames.js:56:9)
    at Connection.sendFrame (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:328:10)
    at ReceiverLink.Link.attach (D:\home\site\wwwroot\node_modules\amqp10\lib\link.js:137:27)
    at ReceiverLink.Link._attemptReattach (D:\home\site\wwwroot\node_modules\amqp10\lib\link.js:252:8)
    at Timeout._onTimeout (D:\home\site\wwwroot\node_modules\amqp10\lib\link.js:240:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

I guess this is well known issue. This should be fixed. I am trying to connect to Azure IoT Hub

**Comment by jtjk** [comment]
I founded workaround:
frames.js lines 52->
  var buffer = builder.get();
  buffer.writeUInt32BE(buffer.length, 0);
  debug('sending frame: ', frame);
  trace('raw: [' + buffer.toString('hex') + ']');
  **if (stream != null)**
    stream.write(buffer, callback);

Yes, this workaround is insane, but I don't have time to debug what is the root cause for that so I use this workaround until something better is coming :)

**Comment by jtjk** [comment]
[https://github.com/noodlefrenzy/node-amqp10/pull/323](url)

**Comment by jtjk** [comment]
Any comments? I am still getting this occasionally

**Comment by sebastus** [comment]
I also get this error quite frequently. Great to see the workaround. Would really prefer an actual fix.
