### ISSUE TITLE
not work well in active-mq-5.14

### ISSUE THREAD

**Issue by kolonse** [noodlefrenzy/node-amqp10#326]
this is error:
```
/root/Admin/node_modules/amqp10/lib/frames.js:64
  stream.write(buffer, callback);
         ^
TypeError: Cannot call method 'write' of null
    at Object.frames.writeFrame (/root/Admin/node_modules/amqp10/lib/frames.js:64:10)
    at Connection.sendFrame (/root/Admin/node_modules/amqp10/lib/connection.js:329:10)
    at Connection._sendCloseFrame (/root/Admin/node_modules/amqp10/lib/connection.js:491:8)
    at Connection._receiveAny (/root/Admin/node_modules/amqp10/lib/connection.js:413:12)
    at Connection._receiveData (/root/Admin/node_modules/amqp10/lib/connection.js:358:8)
    at null.<anonymous> (/root/Admin/node_modules/amqp10/lib/connection.js:516:38)
    at EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (/root/Admin/node_modules/amqp10/lib/transport/net_transport.js:26:49)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
```

**Comment by kolonse** [comment]
i found question! reason is not to set env of active-mq

**Comment by kolonse** [comment]
it's version error! 
```
  amqp10:connection Server AMQP Version: 414d515003010000 vs 414d515000010000 +1ms
  amqp10:client connection error:  { name: 'AmqpVersionError',
  message: 'Credentials Expected - SASL version received: 414d515003010000' } +0ms
  amqp10:client disconnected +1ms
  amqp10:connection stateChange: HDR_SENT => DISCONNECTING , reason: invalidVersion +0ms
  amqp10:trace Rx: 414d5150000100000000001902000000005310c00c04a1004070ffffffff607fff0000006002000000005318c0530100531dc04d02a311616d71703a6465636f64652d6572726f72a137436f6e6e656374696f6e2066726f6d20636c69656e74207573696e6720756e737570706f7274656420414d515020617474656d70746564 +1ms
```

**Comment by kolonse** [comment]
i think this is a version problem，i test it's ok at active-mq-5.12.1

**Comment by kolonse** [comment]
the active-mq-5.14.5 need version 1.3. i try to change amqpVersion of constants.js, but another question display!

**Comment by mbroadst** [comment]
@kolonse there have been a number of related bugs, it appears that ActiveMQ now requires SASL even for anon connections. The error you are getting above indicates that the broker expects SASL, and you are not using it on the client side. Please see details in the linked post on #320.
