### ISSUE TITLE
Azure Node Web App Intermittent Failures

### ISSUE THREAD

**Issue by mitchellcmurphy** [noodlefrenzy/node-amqp10#336]
I created and deployed a NodeJs Web App in Azure today, it relies on websockets and takes a lot of traffic, and it keeps crashing with this error every few hours. I have to force a restart, or delete and replace the API, and I have no idea what the issue is.

Anyone else seeing this error or know how to fix it?

```
Unhandled rejection AmqpDisconnectedError
    at Connection.<anonymous> (D:\home\site\wwwroot\node_modules\amqp10\lib\amqp_client.js:182:23)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection._terminate (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:551:8)
    at Connection._processError (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:351:8)
    at Object.errorHandler (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:282:43)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:203:67)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at Object.event (D:\home\site\wwwroot\node_modules\stately.js\Stately.js:190:52)
    at TlsTransport.<anonymous> (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:516:46)
    at emitOne (events.js:96:13)
    at TlsTransport.emit (events.js:188:7)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\amqp10\lib\transport\tls_transport.js:30:49)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```

**Comment by rahulsahay19** [comment]
Closing this issue as this was because of network blocking issue. working on other wifi network.Thanks!
