### ISSUE TITLE
Error: Out of available handles (Max = undefined)

### ISSUE THREAD

**Issue by ltozi** [noodlefrenzy/node-amqp10#45]
Hi,
After 1 day of inactivity the client gave us this error while performing send again :

```
 [uncaughtException] ERROR: Error: Out of available handles (Max = undefined)
        at new OverCapacityError (/home/azureuser/EMS/backend/20150211114057/node_modules/node-amqp-1-0/lib/exceptions.js:71:11)
        at Session._nextHandle (/home/azureuser/EMS/backend/20150211114057/node_modules/node-amqp-1-0/lib/session.js:259:11)
        at Session.attachLink (/home/azureuser/EMS/backend/20150211114057/node_modules/node-amqp-1-0/lib/session.js:192:34)
        at attach (/home/azureuser/EMS/backend/20150211114057/node_modules/node-amqp-1-0/amqp_client.js:301:27)
        at AMQPClient.send (/home/azureuser/EMS/backend/20150211114057/node_modules/node-amqp-1-0/amqp_client.js:342:13)
        at /home/azureuser/EMS/backend/20150211114057/lib/ems_communication/amqpservicebus/index.js:259:45
        at fn (/home/azureuser/EMS/backend/20150211114057/node_modules/async/lib/async.js:582:34)
        at Object._onImmediate (/home/azureuser/EMS/backend/20150211114057/node_modules/async/lib/async.js:498:34)
        at processImmediate [as _immediateCallback] (timers.js:330:15)
```

cc @teomurgi

**Comment by noodlefrenzy** [comment]
What the... that's weird.  

So you sent some messsages, then left it idle for a day, then tried to re-send?  How many times did you go through this send/idle/send cycle?

Sorry for the trouble, I'm looking into it!

**Comment by ltozi** [comment]
Sorry for the poor informations, but it's a bit difficult to reproduce. I
try to recap the scenario:

I have an instance of AMQPClient that I use only to send messages. There is
a situation where a lot of sends are made in a a loop of five messaegs in
series.

If I'm right,  you try to reset the connection on the first new send
attempt and probably the remaining sent messages cause troubles while
client is still trying to reconnect.




Il giorno Thu Feb 12 2015 at 16:18:06 Michael Lanzetta <
notifications@github.com> ha scritto:

**Comment by noodlefrenzy** [comment]
Ok, thanks for the details.  I'm testing out a potential fix, but obviously it takes a while to reproduce so it might be a bit :)

**Comment by noodlefrenzy** [comment]
I'm really having a problem reproducing this one.  Can you just confirm to me what version you're running against?

I've run the following program:

```
var AMQPClient  = require('node-amqp-1-0');

if (process.argv.length < 3) {
    console.warn('Usage: node '+process.argv[1]+' <settings json file>');
} else {
    var settingsFile = process.argv[2];
    var settings = require('./' + settingsFile);
    var protocol = settings.protocol || 'amqps';
    var serviceBusHost = settings.serviceBusHost + '.servicebus.windows.net';
    if (settings.serviceBusHost.indexOf(".") !== -1) {
        serviceBusHost = settings.serviceBusHost;
    }
    var sasName = settings.SASKeyName;
    var sasKey = settings.SASKey;
    var queueName = settings.queueName;

    var uri = 'amqps://' + encodeURIComponent(sasName) + ':' + encodeURIComponent(sasKey) + '@' + serviceBusHost + '/' + queueName;

    var msgVal = 0;
    var secs = 0;
    var secsUntilSend = 1280;

    var sendCB = function(id, tx_err, state) { console.log(id + ' Dispo: ', state); };
    var client = new AMQPClient(AMQPClient.policies.ServiceBusQueuePolicy);
    for (var idx = 0; idx < 5; ++idx) {
        client.send({"DataString": "From Node", "DataValue": msgVal}, uri, sendCB.bind(null, msgVal));
        msgVal++;
    }
	console.log('\nWaiting ' + (secsUntilSend / 60) + ' minutes until next send\n');
    setInterval(function () {
        ++secs;
        if (secsUntilSend === secs) {
            console.log('Sending at interval ' + secsUntilSend);
            secsUntilSend *= 2;
            secs = 0;
            for (var idx = 0; idx < 5; ++idx) {
                client.send({"DataString": "From Node", "DataValue": msgVal}, uri, sendCB.bind(null, msgVal));
                msgVal++;
            }
            console.log('\nWaiting ' + (secsUntilSend / 60) + ' minutes until next send\n');
        }
    }, 1000);
}
```

Which basically, given the right settings file, will connect to a queue, send 5 messages, then wait long enough to ensure it gets disconnected, send 5 more, then wait twice as long, ...

I've run it until the secsUntilSend got to 5120, with no problem.  I see it re-establishing the connection, then the session, then the sender link, and only _then_ sending the 5 messages.

Note that when it re-establishes the session is when it comes to an agreement on what maxHandles should be - can you enable debugging (setenv DEBUG=amqp10*), trap output, and let me know what you get when you grep for "On BEGIN_RCVD"?  That prints out the session parameters, the last of which is the maxHandles.  It has sensible defaults, too, when it sees undefined, so that's why I'm so confused.

Anyway, I'll still keep trying to diagnose it on my side, but any additional information from you is much appreciated.

**Comment by ltozi** [comment]
I'me running the latest version. Anyway, is a bit difficult (as you said
too ) to reproduce the problem. I'll try ASAP to let you know other
informations.

Thnks

Il giorno Thu Feb 12 2015 at 22:21:39 Michael Lanzetta <
notifications@github.com> ha scritto:

**Comment by noodlefrenzy** [comment]
Ugh, my worst nightmare - a bug you have that I can't reproduce!  I'll keep trying, and in the meantime I'll do another code walkthrough to see if I can figure out where things are going wrong.  If you could send me a gist of your code or point me to a bitbucket or github repo, that would we useful.

**Comment by mbroadst** [comment]
This was based on an incredibly old version of the code, please try to update to the latest version and let us know if you still have this issue. In the meantime closing for lack of activity.
